### ISSUE TITLE
Patched FiraCode Only Works for First Set of PowerLevel 10K Glyphs

### ISSUE THREAD

**Issue by louisefindlay23** [tuanpham-dev/code-server-font-patch#1]
Followed the instructions to patch code-server with FiraCode (`/app/code-server` directory since using LS Docker) and add to `settings.json` but only the first set of glyphs show in my ZSH prompt with Powerlevel10k. 

Is the patched version of Fira Code, the Nerd Font version?

![Powerlevel10k Configuration](https://user-images.githubusercontent.com/26024131/172598996-efd5fa1d-2fb9-417c-a731-91a2fd1510c0.png)

![Powerlevel10K Prompt](https://user-images.githubusercontent.com/26024131/172598917-7cef9d74-8146-40ee-8ecc-3c2207f14a70.png)

![Code-Server settings.json](https://user-images.githubusercontent.com/26024131/172599555-ca149cca-ec07-444c-96ea-8cbd195216a5.png)

**Comment by tuanpham-dev** [comment]
@louisefindlay23 - I think you have to install nerd font. Try these steps:

1. Remove css added in `/usr/lib/code-server//lib/vscode/out/vs/workbench/workbench.web.main.css`
2. Download this repository: https://github.com/uncon/MesloLGSNF-web-fonts
3. Append `stylesheet.css` to `resources/fonts.css`
4. Copy `fonts` folder to `resources/fonts` folder
5. Run `patch.sh` again
